oVirt/ovirt-imageio

CODEOWNERS
CODE_OF_CONDUCT.md

Add standard files based on https://github.com/oVirt/ovirt-imageio/community.

Community - add code of conduct and CODEOWNERS

---

test/client_test.py

Add stress test uploading and downloading empty image in a loop. This
reproduce the issue when the io executor close the destination backend
before one of the workers clone it, causing a successful transfer to
fail (#23).
Adding this tests before 1a7acfe reproduces the issue quickly and reliably:
https://github.com/nirs/ovirt-imageio/runs/4860940233

test: Add client stress test

---

ovirt_imageio/_internal/server.py
test/server_test.py

If a user runs ovirt-imageio or ovirt-imageioctl with invalid
configuration directory, we silently ignored the directory since it has
no configuration files, and failed later when with a confusing error
message.
Change server.load_config() to validate that the configuration directory
contains at least one configuration file. This will also fail if the
default configuration directory (/etc/ovirt-imageio) becomes broken.
Failing fast will help users to fix the issue quickly.
Example failure with this change:
$ ./ovirt-imageio -c test/conf
Server failed
Traceback (most recent call last):
File "/home/nsoffer/src/ovirt-imageio/ovirt_imageio/_internal/server.py", line 38, in main
cfg = load_config(args.conf_dir)
File "/home/nsoffer/src/ovirt-imageio/ovirt_imageio/_internal/server.py", line 93, …

server: Fail fast with invalid config directory

---

CODEOWNERS

Moving to different project, removing myself from code owners not to
block code reviews.

CODEOWNERS: Remove me from code owners

---

ovirt-imageio.spec.in

Update changelog for rlease 2.4.1.

Release 2.4.1

---

setup.py

Fix bug tracker url in setup.py to point to github.
Fixes #45

Fix upstream bug tracker url

---

RELEASE.md

- Remove stale info about gerrit
- Document how to create new release in github
- Document how to create new release for pypi
- Update RHEL release section
- Improve document organization
Fixes #46

RELEASE.md: Update release instructions

---

ovirt_imageio/_internal/version.py

version: Bump version to 2.4.3

---

ovirt-imageio.spec.in

Release 2.4.3

---

ovirt_imageio/_internal/version.py

version: Bump to 2.4.6

---

ovirt_imageio/client/_download.py
ovirt_imageio/client/_options.py
ovirt_imageio/client/_ovirt.py
test/client_options_test.py

Show download phases during download-disk.
Rebased on #110

Download phase

---

ovirt_imageio/_internal/io.py
ovirt_imageio/client/_api.py
ovirt_imageio/client/_tool.py
test/io_test.py

Reverts oVirt/ovirt-imageio#107

Revert "ovirt-img: Terminate cleanly on signals"

---

ovirt-imageio.spec.in

Release 2.4.6-1

---

CODEOWNERS

Add me to code owners to get automatic pull
request reviews as project maintainer.

CODEOWNERS: Add me to code owners

---

ovirt_imageio/_internal/version.py

version: Bump version to 2.4.7

---

.github/workflows/containers.yml

Lists in yaml are formatted as comma-separated items.
Fix: https://github.com/oVirt/ovirt-imageio/commit/a17bd41075775e712b5589923c03d06d6cae3c9d

Container workflow fix

---

docs/container.md

Add documentation for the containerized imageio
that is provided, showing how to build and run the image.

docs/container.md: document container

---

ovirt-imageio.spec.in

Release 2.4.7-1

---

ovirt_imageio/_internal/version.py

version: Bump version to 2.4.8

---

ovirt-imageio.spec.in

Based on #186:
- Squash fix commits to one commit
- Add missing signed-off-by

Reorder python builds

---

README.md

Replace old Copr build url to new one.

readme: fix Copr build status badge
