oVirt/ovirt-imageio

data/README, examples/nbd.json, ovirt_imageio/_internal/auth.py, ovirt_imageio/_internal/backends/__init__.py, ovirt_imageio/_internal/config.py, ovirt_imageio/_internal/http.py, test/admin_test.py, test/auth_test.py, test/backends_test.py, test/testutil.py
We used 60 seconds timeout for disconnecting inactive clients. This is
too long to protect from bad clients leaving open connections, and too
short for applications that need long timeout[1].
Change the default timeout to 15 seconds, configurable via
daemon:auth_timeout. This timeout is used for new unauthorized
connections. If a connection does not authorize within this timeout, it
is disconnected.
When a connection is authorized during the first request, the connection
timeout is increased to ticket.inactivity_timeout. The default value is
60 seconds, configurable via daemon:inactivity_timeout.
Application with special needs can request a larger timeout when
creating an image transfer. Engine need to include the transfer
inactivity timeout in the ticket.
[1] …
=> http: Configurable inactivity timeout

ovirt_imageio/_internal/backends/nbd.py
If the backend of an idle connection is closed when ticket is canceled,
the backend is closed again when the idle connection is closed. Closing
backend multiple times is designed to be safe, but we should really log
only once, when actually closing the nbd client.
The same behavior is already implemented in the file backend.
=> backends/ndb: Avoid double close logs

docker/Dockerfile.centos-8, docker/Dockerfile.centos-9
Install ovirt-release-master from copr instead of stale
resources.ovirt.org.
=> docker: Update centos containers repos

CODEOWNERS
Add @oVirt/ovirt-documentation to watch the docs/ and README.md.
=> CODEOWNERS: Add oVirt documentation team

docker/Dockerfile.centos-8, docker/Dockerfile.centos-9, docker/Dockerfile.fedora-34, docker/Dockerfile.fedora-35
quay.io never updates our containers unless we change the list of
packages, so we don't get updates when new packages are released, and we
fail to detect regressions in packages we depend on.
Add a version to the RUN line. The version should be modified each time
we want to rebuild the containers.
Adding a workflow the build the container is probably better, but
require more work.
=> docker: Disable quay.io caching

go/backend.go, go/http/http.go, go/http/http_test.go, ovirt-img/nbd/nbd.go, ovirt-img/nbd/nbd_test.go
Backend.ReadAt() implements the io.ReaderAt interface. This is similar
to pread(2)[1] and our python client library ImageioClient.read()[2]
The change exposes some issues in the current code:
- All sizes should use int64 instead of uint64. This is what standard
library is using (e.g. io.Reader). We use uint64 because of libnbd.
- The nbd and http tests are mostly identical. Move the common parts of
the tests to the imageio module. This will also be useful for 3rd
party projects that want to create new backends.
[1] https://man7.org/linux/man-pages/man2/pread.2.html
[2] https://github.com/oVirt/ovirt-imageio/blob/master/ovirt_imageio/client/_api.py#L377
=> ovirt-img: Implement Backend.ReadAt

ovirt_imageio/_internal/nbd.py, ovirt_imageio/_internal/qemu_nbd.py, test/nbd_test.py, test/qemu_nbd_test.py
qemu-nbd 6.2.0 introduced a bug[1] when accessing raw image extents. The
first call works correctly, but the next calls the entire image is
reported as data.
Example failure:
>>> pprint(c.extents(0, c.export_size))
DEBUG:nbd:Sending NBD_CMD_BLOCK_STATUS handle=0 offset=0 length=1073741824 flags=0
DEBUG:nbd:Extent length=1073741824 flags=3 context=0
DEBUG:nbd:Extent length=1073741824 flags=1 context=1
{'base:allocation': [Extent(length=1073741824, flags=3)],
'qemu:allocation-depth': [Extent(length=1073741824, flags=0)]}
We got the flags = 3  (NBD_STATE_HOLE | NBD_STATE_ZERO)
>>> pprint(c.extents(0, c.export_size))
DEBUG:nbd:Sending NBD_CMD_BLOCK_STATUS handle=1 offset=0 length=1073741824 flags=0
DEBUG:nbd:Extent length=1073741824 flags=0 context=0
DEBUG:nbd:Extent length=1073741824 flags=1 …
=> qemu_nbd: Disable allocation depth for raw format

ovirt_imageio/_internal/backends/__init__.py, ovirt_imageio/_internal/io.py, ovirt_imageio/_internal/nbd.py, ovirt_imageio/_internal/qemu_nbd.py, test/nbd_test.py, test/qemu_nbd_test.py
When using a thread pool we try to reuse the connection backend by
passing the connection backend to the first worker instead of cloning
it. This introduce some issues:
- The backend is closed twice: once by the worker, and again by the
connection. This is safe since closing backend twice does nothing, but
dirty. Will break if we try to use the backend after a copy.
- With very small images, the first worker may close the original
backend before another worker try to clone it. This is unlikely to
happen with real images but can break the tests.
Fix the issues by introducing a backend wrapper, overriding close() to
disconnect from the wrapped backend instead of closing it. This ensures
that dst is never closed before it is cloned, and that it is closed
exactly once.
Another approach to fix …
=> io: Fix backend closing in executor.

ovirt_imageio/_internal/auth.py, ovirt_imageio/_internal/errors.py, ovirt_imageio/_internal/handlers/checksum.py, ovirt_imageio/_internal/handlers/extents.py, ovirt_imageio/_internal/handlers/images.py, ovirt_imageio/_internal/handlers/tickets.py, test/auth_test.py, test/handlers/tickets_test.py, test/testutil.py
Log the transfer id instead of the ticket id for easier debugging.
The transfer id is already used in other components for tracking 
a transfer.
Fixes #26.
=> Replace ticket id with transfer id

ovirt-img/nbd/nbd.go
- Exit with clear error instead of panic if extent callback failed
- Improve comment about EINTR in blockStatus()
=> ovirt-img: Improve error handling and documention

Makefile, ovirt_imageio/_internal/auth.py, ovirt_imageio/_internal/measure.py, test/auth_test.py, test/measure_test.py, tox.ini
Speed up ranges calculations when completing requests and computing transferred size.
- Make it easier to run the benchmarks
- Improve the benchmarks simulating real transfer with 2 kinds of clients (nbdcopy, imageio)
- Improve benchmarks output
- Improve measure tests
- Remove python 2 only `Range.__ne__`
- Add `Range.__repr__` for easier debugging
- Add `Range.__slots__` to minimize Range creation time
- Speed up `Range.__lt__`
- Remove unneeded sorting during merge
- Add `RangeList` class for managing ranges
The actual speedup is very small, but the code is cleaner and easier to maintain.
Fixes #29.
=> Speed up ranges calculations

ovirt_imageio/_internal/auth.py, test/auth_test.py
When using read-write ticket, we don't report the number of transferred
bytes, so there is no point to track the ranges.
This is so far the biggest optimization, lowering the overhead per
request by 20%. However since engine never use read-write mode, this
does not improve real flows.
The most important benefit is proving that additional optimization in
measuring ranges is not effective, since 80% of the time is spent
elsewhere.
```
test_run_benchmark[ro-nbdcopy-1] 1 workers, 25600 ops, 1.884 s, 13588.32 ops/s
test_run_benchmark[ro-nbdcopy-2] 2 workers, 25600 ops, 2.229 s, 11483.24 ops/s
test_run_benchmark[ro-nbdcopy-4] 4 workers, 25600 ops, 2.305 s, 11104.09 ops/s
test_run_benchmark[ro-nbdcopy-8] 8 workers, 25600 ops, 2.410 s, 10623.58 ops/s
test_run_benchmark[ro-imageio-1] 1 workers, …
```
=> auth: Don't track ranges for read-write ticket

ovirt_imageio/_internal/qemu_nbd.py, ovirt_imageio/admin/_api.py, ovirt_imageio/admin/tool.py
Make it easy to profile the server using the ovirt-imageioctl
tool or the admin client library.
Example usage:
ovirt-imageioctl add-ticket examples/json
ovirt-imageioctl start-profile
examples/imageio-client upload src-image https://localhost:54322/images/nbd
ovirt-imageioctl stop-profile
Not documented yet.
=> Add profiling support

ovirt-img/go.mod, ovirt-img/go.sum
This is the first stable release of the Go bindings.
=> ovirt-img: Upgrade libnbd to v1.12.0

ovirt_imageio/_internal/backends/file.py, ovirt_imageio/_internal/backends/http.py, ovirt_imageio/_internal/backends/memory.py, ovirt_imageio/_internal/backends/nbd.py
The open and close logs are mainly needed for debugging resource
management, but we logged them in INFO level. This is OK in the daemon
but problematic for the client code, crating unwanted noise in
application using the client library.
Tested using backup stress test.
=> backends: Log open and close in debug level

ovirt_imageio/_internal/qemu_nbd.py, ovirt_imageio/client/_api.py, test/qemu_nbd_test.py
Previously we use --cache=writeback and --aio=threads so we can access
images on file system that does not support direct I/O. This is
sometimes faster than --cache=none and --aio=native, but typically give
less consistent results, and pollute the page cache with image data,
which is mostly likely will never be used.
When uploading and downloading images on a hypervisor, using the page
cache can be harmful and cause sanlock timeouts when the kernel try to
flush huge images to the underlying storage.
Future qemu-img and qemu-nbd are expected to implement "auto" cache and
aio modes, selecting --cache=none and --aio=native if possible. This
change implements this in our qemu_nbd wrapper so we can use this now
with current qemu version.
When starting qemu_nbd.Server(), if cache was not …
=> qemu_nbd: Select cache and aio automatically

ovirt-imageio.spec.in, ovirt_imageio/_internal/version.py
Start next development cycle for oVirt 4.5.0.
- Bump version to 2.4.2
- Fix source url in the spec
=> Start 2.4.2 development cycle

.github/workflows/ci.yml
Uses ovirt/upload-rpms-action so RPM build artifacts are consumable by
OST runs.
Signed-off-by: Martin Perina <mperina@redhat.com>
=> Use ovirt/upload-rpms-action

docker/Dockerfile.centos-8, setup.py, test/backup_test.py, tox.ini
We want to build also python 3.8 version of the common and client
packages, needed by ovirt python sdk. Adding python 3.8 to the container
enables the build and the tests.
python38-systemd is not available, hopefully this is a pure python
package and python3-systemd will works for the tests.
=> docker: Add python 3.8 to el8 container

.copr/Makefile
Switching to setuptools broke the copr Makefile, since
python3-setuptools is not installed in the Fedora mock environment
creating the source rpm.
Fixes: 4ab3229b55bc (tox: Fix tests with multiple python versions)
=> copr: Install python3-setuptools

docker/Dockerfile.centos-8, docker/Dockerfile.centos-9, docker/Dockerfile.fedora-34, docker/Dockerfile.fedora-35, docker/Makefile, docs/development.md, ovirt-imageio.spec.in
- Fix Fedora copr builds, broken by recent change to use setuptools.
- Add python3-setuptools to the docker files to make the requirement explicit
- Update docs/developmemnt.md to include python3-steuptools to match the spec and docker files
- Update stale notes about automation packages files
- Fix docker Makefile so it pushes to quay.io
=> Build and docs improvements

Makefile, ci/test.sh, docs/development.md, test/backup_test.py, test/conftest.py
- Fix the way we build the extension module in the Makefile
- Remove unneeded "make" call in the CI, and improve docs for running the tests
- Improve the way we create the base image for the backup tests so we can avoid long timeouts in the CI, and run the tests on all tested distros.
- Document how to create and delete the test images
=> Testing and documentation improvements

ovirt-imageio.spec.in
Adds python38-client and python38-common packages to support oVirt
Ansibe Collection running on ansible-core-2.12 on EL8.
Signed-off-by: Martin Perina <mperina@redhat.com>
=> Add Python 3.8 client and common packages

ovirt-imageio.spec.in
While resolving conflicts, some comments were removed, and unneeded
Requires was added.
Fixes: b023883aef28 (Add Python 3.8 client and common packages)
=> spec: Fix bad rebase

ovirt_imageio/_internal/http.py
In commit d5e9c757e0a4 (http: Configurable inactivity timeout) we
changed the default timeout from 60 seconds to 15. The reasoning was
that clients have no reason to connect and keep the connection idle for
long time. Once a client connects, it is expected to start sending
requests. On the first request, the socket timeout is replaced by the
ticket inactivity timeout, set by the user creating the transfer.
Turns out that there is a valid use case for idle clients, and the
shorter timeout breaks downloads of big images (reproduced with 8 TiB
image. The failure flow is:
1. Client connects and send an EXTENTS request.
2. While EXTENTS request is collecting data, client connects multiple
downloads connections.
3. The connected download threads wait on a queue for work, but since
EXTENTS …
=> http: Revert the default timeout to 60 seconds

examples/checksum
Add simple example showing how to use client.checksum() to compute a
checksum for local image.
This is mainly useful for benchmarking, for example comparing to
sha256sum, or blksum.
=> examples: Show how to use client.checksum()

.copr/Makefile, ovirt_imageio/_internal/version.py
Copr runs "make srpm" in a directory not owned by the current user. This
breaks git commands and we get the wrong version number (e.g. 2.4.4-1)
instead of (2.4.4-0.timestamp.githash). The wrong version number break
users and OST, never getting the latest version.
=> copr: Workaround for CVE-2022-24765 fix

data/README, ovirt_imageio/_internal/config.py
When we added configurable inactivity timeout, we added also auth
timeout but it was never used. The value was hardcoded to 15 seconds in
2.4.3 and was reverted back to 60 seconds in 2.4.5.
Fixes: d5e9c757e0a4 (http: Configurable inactivity timeout)
=> config: Remove unused daemon:auth_timeout

.copr/Makefile, build-aux/release
- Fix error handling in build-aux/release script
- Remove unneeded workaround for copr build
Example copr build with from this change:
https://copr.fedorainfracloud.org/coprs/nsoffer/ovirt-imageio-preview/build/4565080/
=> Build cleanups

.gitignore, ovirt_imageio/_internal/backends/file.py, ovirt_imageio/_internal/backends/http.py, ovirt_imageio/_internal/blkhash.py, ovirt_imageio/_internal/config.py, ovirt_imageio/_internal/directio.py, ovirt_imageio/_internal/io.py, ovirt_imageio/_internal/nbd.py, ovirt_imageio/_internal/nbdutil.py, ovirt_imageio/_internal/ops.py, ovirt_imageio/_internal/units.py, ovirt_imageio/_internal/util.py
There are many repetitions of `1024**2` and
`1024**3` for MiB and GiB, respectively.
Instead, add constants and use them
to make it more readable.
Fixes: #31
=> imageio: add unit constants

test/admin_tool_test.py
In admin_tool_test, srv fixture is parametrized
to create two servers with built ovirt-imageio,
with a terminate at the end, between runs.
However, if runs do happen too fast
it may try to create the next server socket
before the previous is closed, resulting in
an "address already in use" error.
Add a wait() after terminate() to ensure we do
not run into such issue.
=> admin_tool_test: add wait at srv fixture

ovirt_imageio/_internal/uhttp.py
A recent change in cpython broke autobind of abstract
unix socket in linux, causing bind calls with an
empty string to be bound to '\0' instead of a
random address (expected). This results in an
'address already in use' error when consecutive empty
string binding is used.
While we wait for this issue to be solved, we need
to enforce a random address to be used for empty
strings in the abstract space.
Related: python/cpython#94821
=> uhttp: force empty string to random addr

.github/workflows/ci.yml, ci/test.sh
On centos 8 we run the tests twice both with python 3.6
(platform python) and python 3.8. This doubles the
run time and makes it harder to check failures.
Other distros only run a single python environment
tests, but checks for all of them, creating a lot
of unnecesary noise in the logs.
Separate centos-8 enviornments for py36 and py38
to allow parallel execution. Other distributions
should run only a specific python environment
that matches the one they have installed.
Fixes: https://github.com/oVirt/ovirt-imageio/issues/90
=> ci: split centos 8 jobs for py36 and py38

ovirt_imageio/client/_ui.py, test/client_ui_test.py
Previously we updated the progress up to 10 times per second, and we
displayed fractional percent values (e.g. 12.57%). This is too noisy and
creates too many uninteresting updates. It also calls
time.monotonic_time() on every update to check if it is time to update
which is waste of resources for very little benefit.
Change the progress to show integer values (12%) and update the progress
only when the progress value changes. With this change we update the
progress up to 100 times during a transfer.
=> client: Less noisy progress

ovirt_imageio/client/_ui.py, test/client_ui_test.py
- Spelling
- Make private attributes private
- Remove wrong check
- Ensure closed progress is not updated
- Modernize ProgressBar._draw
- Make conditional expression more clear
- Use unit constants in ui tests
Rebased on top of #102.
=> Progress bar cleanups

ovirt-imageio.spec.in, setup.py
The ovirt-imageio-client package installs now the ovirt-img tool, and
requires python3-ovirt-engine-sdk4.
This is part of #72
=> ovirt-img: Package as part of ovirt-imageio-client

ovirt_imageio/client/_options.py, ovirt_imageio/client/_ovirt.py, ovirt_imageio/client/_tool.py, test/client_options_test.py
More general options parsing allowing mixing of command line
arguments and config options. Add log file options using the
new infrastructure.
This is part of #72
=> ovirt-img: Add logging options

ovirt_imageio/client/_ui.py, test/client_ui_test.py
Transferring an image include several phases that may take several
seconds, and we want to show what the tool is doing. When we finish, we
want to show that the operation was completed. If we failed, we want to
show a short failure message even if we use log errors to file.
Add an optional phase argument to ProgressBar. If the phase is set, it
is displayed at the end:
[ ---- ] 0 bytes, 0.00 s, 0 bytes/s | setting up
The caller can change the phase by setting a new value:
pb.phase = "downloading image"
This will redraw the progress bar:
[   0% ] 0 bytes, 0.00 s, 0 bytes/s | downloading image
This change only adds the infrastructure, no change yet in the actual
commands.
=> client: Show progress phase

ovirt_imageio/client/_options.py, ovirt_imageio/client/_ovirt.py, test/client_options_test.py
In ovit-img log_file defaults to /dev/stderr fd,
and is passed to logging configurator through
filename argument.
However, this is not correct, filename only is
used for files. File descriptions shall go
as stream parameters.
Otherwise the tool breaks with
'OSError: [Errno 29] Illegal seek'
in an internal logging module.
Reproduced with Python 3.6 in CentOS Stream 8.
To solve it, default log_file to None instead, so
that logging configuration does not use a filename
and falls back to the stream argument, which defaults
to stderr.
Fixes: #113 
Fixes: a2bbe122cc85d08dd5ab60e6d2438b54b1f11e6b
=> ovirt-img: fix logging config

test/client_options_test.py
Test that parsing options without arguments is same as --help.
Fixes: 744799e00467 (ovirt-img: Fix running without arguments)
=> ovirt-img: Add missing tests

ovirt_imageio/_internal/io.py, ovirt_imageio/client/_api.py, ovirt_imageio/client/_io.py, ovirt_imageio/client/_tool.py, test/client_io_test.py
Handle SIGINT and SIGTERM by terminating qemu-nbd and triggering normal cleanup flow, removing the temporary directory and finalizing the image transfer.
When qemu-nbd is terminated, the worker threads may log noisy and unhelpful tracebacks. Since we already re-raise the first worker error, we can suppress these tracebacks.
When the tool is terminated by signal, we suppress errors from the tool (e.g. BrokenPipe). Otherwise we log one traceback on errors.
Here are some examples:
Terminated by SIGINT:
```
$ ./ovirt-img download-disk -c engine 07b53997-7b4c-4861-bf38-f6fbb29921d9 dl.qcow2
^C[   5% ] 2.50 GiB, 3.66 seconds, 698.52 MiB/s                                  
2022-07-27 14:29:58,892 ERROR   (MainThread) [tool] Terminated by signal 2
```
qemu-nbd killed during transfer:
```
$ …
```
=> ovirt-img: Terminate cleanly on signals

ovirt_imageio/_internal/io.py, ovirt_imageio/_internal/qemu_nbd.py, ovirt_imageio/client/_api.py, ovirt_imageio/client/_app.py, ovirt_imageio/client/_io.py, ovirt_imageio/client/_tool.py, test/client_io_test.py, test/qemu_nbd_test.py
Register signals handlers before running the command, and handle
signals gracefully.
When terminated by signal, log an error instead of a traceback, since
this is expected condition. Since termination by SIGINT is typically
initiated by a user log info level message.
For any other error, log a traceback to make it easy to report useful
bug reports.
=> Terminate gracefully on signals

ovirt_imageio/client/_download.py, ovirt_imageio/client/_options.py, ovirt_imageio/client/_ovirt.py, ovirt_imageio/client/_tool.py, ovirt_imageio/client/_upload.py, test/client_options_test.py
Add upload-disk sub-command for upload disks.
```
$ ./ovirt-img upload-disk -h
usage: ovirt-img upload-disk [-h] [-c CONFIG] [--engine-url ENGINE_URL]
[--username USERNAME]
[--password-file PASSWORD_FILE] [--cafile CAFILE]
[--log-file LOG_FILE] [--log-level LOG_LEVEL]
[--max-workers MAX_WORKERS]
[--buffer-size BUFFER_SIZE] -s STORAGE_DOMAIN
[-f {raw,qcow2}] [--preallocated] [--disk-id ID]
filename
positional arguments:
filename              Path to image to upload. Supported formats: raw,
qcow2, iso.
optional arguments:
-h, --help            show this help message and exit
-c CONFIG, --config CONFIG
If set, read specified section from the configuration
file.
--engine-url ENGINE_URL
ovirt-engine URL. If not set, read from the specified
config section (required).
--username USERNAME …
```
=> ovirt-img: add upload-disk

ovirt_imageio/client/_upload.py
Add '--name' option to the 'upload-disk' command
to allow users to define a custom alias name
for the new uploaded disk. If ommited, default
behaviour remains, taking the source image filename
as an alias.
```
usage: ovirt-img upload-disk [-h] [-c CONFIG] [--engine-url ENGINE_URL]
[--username USERNAME]
[--password-file PASSWORD_FILE] [--cafile CAFILE]
[--log-file LOG_FILE] [--log-level LOG_LEVEL]
[--max-workers MAX_WORKERS]
[--buffer-size BUFFER_SIZE] -s STORAGE_DOMAIN
[-f {raw,qcow2}] [--preallocated]
[--disk-id DISK_ID] [--name NAME]
filename
....
--name NAME           Alias name for the new disk. If not specified, name
will correspond with the image filename.
```
Closes: #121
=> ovirt-img: add name option for disk

ovirt_imageio/client/_options.py, test/client_options_test.py
Add --version option to ovirt-img tool to show current version:
```
$ ./ovirt-img -h
usage: ovirt-img [-h] [--version] {download-disk,upload-disk} ...
Transfer disk images
optional arguments:
-h, --help            show this help message and exit
--version             show program's version number and exit
commands:
{download-disk,upload-disk}
download-disk       Download disk
upload-disk         Upload disk
```
```
$ ./ovirt-img --version
ovirt-img 2.4.6
```
Fixes: #125
=> ovirt-img: add --version option

Makefile, docs/development.md
Add venv target to the Makefile, which automatically
creates the Python virtual environment in a
consistent folder and installs all requirements in a
single step.
=> Makefile: add venv target

RELEASE.md
Small update to the RELEASE document, that includes:
- Remove the step about downloading the RPMs in Upstream.
It is not required now.
- Show how to enable the Fedora RCM tools repository for
installing rhpkg.
- Set public key algorithm for pushing the package with rhpkg.
- Small typo.
=> RELEASE.md: small update

containers/centos-9.containerfile
A recent change to DNF COPR plugin [1] makes 'epel-9' the default chroot
used for CentOS Stream 9. Let's specify the 'centos-stream-9' chroot
name that we use in oVirt's COPR expliclty.
[1] https://github.com/rpm-software-management/dnf-plugins-core/pull/459
Signed-off-by: Marcin Sobczyk <msobczyk@redhat.com>
=> containers: Specify COPR chroot explicitly

test/backends/http_test.py
Recent HTTPRequestHandler changes avoid urls that
start with '//' to protect against open redirect
attacks (see https://github.com/python/cpython/commit/4abab6b603dd38bec1168e9a37c40a48ec89508e).
Server url in the http test have no path,
therefore the handler that is used in the
test receives the root path, resulting in
requests starting with '//' when the Backend
tries to get the extents, which break in the
pipelines for recent Python 3.10 versions.
This is not a realistic scenario and not
something the library needs to handle.
Is better to change the url to a more
realistic scenario, and since we want
to test image handling, have
`/images/ticket-id` in the url path.
=> http: avoid double slashes in url

ovirt_imageio/client/_options.py, ovirt_imageio/client/_ovirt.py, ovirt_imageio/client/_upload.py, test/client_options_test.py
On disk-upload, ovirt-img  probes a disk after
creation during a fixed time, until it reaches an
OK status (or timeout).
If there is an error in the creation and disk becomes
DiskStatus.ILLEGAL, users have to wait for the timeout.
We need to handle this error status and fail loudly.
Add an option, only available through config file,
to change the timeout waiting for disk creation.
This is a fine-gran configuration that should be
fine as default for most cases, but may be
interesting to modify it for stress tests,
or slow networks, etc.
Fixes: https://github.com/oVirt/ovirt-imageio/issues/117
=> ovirt-img: disk creation loop

containers/requirements.txt, test/backends/file_test.py, test/backends/nbd_test.py, test/conftest.py, test/handlers/checksum_test.py, test/handlers/extents_test.py, test/nbd_test.py, test/ops_test.py, test/storage.py, tox.ini
Update userstorage to v0.5.1.
Set pytest.xfail as handler for missing
storage.
Currently, all tests that rely on userstorage employ
the Backend wrapper only to add a couple attributes.
With recent update, context management is natively
supported by userstorage library. On the other
hand, not all test require the Backend additional
attributes.
We can avoid using the Backend wrapper completely
for tests that do not require the attributes.
Otherwise, the Backend can just wrap the
storage from within the userstorage context (i.e.,
after the storage is setup), so we avoid the
__enter__() and __exit__() overrides.
=> update userstorage version

ovirt_imageio/_internal/server.py, test/containerized_test.py
Add a -t/--ticket option to the ovirt-imageio
server CLI, so that it can optionally load a
ticket directly as the server starts.
```
$ ovirt-imageio -c config -t path/to/ticket.json
2022-09-22 12:36:51,082 INFO    (MainThread) [server] Starting (hostname=fedora pid=3113040, version=2.4.7)                                                   
2022-09-22 12:36:51,082 DEBUG   (MainThread) [services] Creating remote.service on port 54322                                                                  
...
2022-09-22 12:36:51,087 INFO    (MainThread) [server] Initial ticket: examples/file.json
2022-09-22 12:36:51,087 INFO    (MainThread) [services] control.service listening on 'test/daemon.sock'
2022-09-22 12:36:51,087 DEBUG   (MainThread) [services] Starting remote.service 
2022-09-22 …
```
=> Load ticket as the Server starts

examples/conf.d/daemon.conf, ovirt_imageio/_internal/config.py, ovirt_imageio/_internal/server.py, test/conf.d/daemon.conf, test/conf/daemon.conf, test/conf/proxy.conf, test/conf/user-tls.conf
When running without systemd (e.g. in a container) we don't need to notify system. Add new configuration "daemon:systemd_enable" to allow disabling systemd integration. This removes the runtime dependency on the systemd.daemon package, simplifying deployment.
Disable systemd integration in all the test and example configurations system they never start the daemon as a systemd service.
=> server: Make systemd optional

ovirt_imageio/_internal/config.py, ovirt_imageio/_internal/server.py
When running in a container we will load the ticket using --ticket option so we don't need the control service.
=> Make control service optional

Makefile, container/Containerfile, container/conf.d/daemon.conf
Start a container image for running imageio and container.
Using a container, the user will run an image transfer pod for every
transfer, exposing the pod for remote access, and connecting the
relevant storage the pod. When the transfer is done, the user will
unexpose the pod and terminate it.
In this mode the imageio server will serve one ticket, injected into the
pod when starting the pod, instead of adding a ticket using the control
service.
Signed-off-by: Nir Soffer [nsoffer@redhat.com](mailto:nsoffer@redhat.com)
Signed-off-by: Albert Esteve [aesteve@redhat.com](mailto:aesteve@redhat.com)
=> Containerized imageio deployment

.github/workflows/containers.yml
Build project containers (currently four)
and push them every week to update at least
the underlaying OS.
Fixes: #13
=> ci: build containers automatically every week

.github/workflows/containers.yml
Based on the examples[1] the quay.io username should be part of the `registry` value. Hopefully this will find the image built in the build step `localhost/image` and will push it to `quay.io/ovirt/image`.
[1] https://github.com/redhat-actions/push-to-registry#examples
=> Fix push to quay.io

ovirt_imageio/_internal/backends/__init__.py, ovirt_imageio/_internal/backends/http.py, test/backends/http_test.py
Support HTTP connections without the secure
extension in the http backend. This way, the
backend can handle both http and https url
schemes from the http client.
If the url is non-secure, then we create
an http.HTTPConnection instead, and simply skip
creating the TLS context.
=> backend.http: support non-secure connections

tox.ini
Previously we used `sitepackages=True` to get access to the `systemd.daemon` python package, installed by `python3-systemd` package.
Since commit ffa7337ec3bf (server: Make systemd optional) we always disable systemd daemon during the tests, so this access is not needed.
Disabling access to system packages allows running the tests when `pytest` is installed on the host via the package manager. This is very helpful since some projects (e.g. `blkhash`) require the system `pytest`. Before this change I had to remove the `pytest` package before running imageio tests.
=> tox: Always disable sitepackages

container/Containerfile, container/app/entrypoint.py, ovirt_imageio/_internal/util.py, ovirt_imageio/client/_api.py
Include qemu-nbd in the container to make it
easier for users to use the containerized imageio
server.
The container now runs with a script as an
ENTRYPOINT. The script runs as a program that
can receive additional command line parameters.
The script is basically a launcher for the two
main services involved:
- qemu-nbd serving the image
- ovirt-imageio exposing the image through http
This commit removes support for file ticket, only
nbd tickets are implicitely used. This is better,
as nbd does much of the hard work for us, so will
perform better.
Users will not have to worry about
the ticket anyway, the ticket is also generated
automatically, so no need to mount the ticket
inside the container, or give an environment
variable. Users can set the ticket ID in the
command line, or use the …
=> container: serve image with nbd

.github/workflows/containers.yml, containers/Makefile
Current containers Makefile builds a different
image for each distro, which then gets pushed
into a different repository of the oVirt
organization in quay.io.
Changing distros in this fashion requires
creating new repositories, doing clean up
of the older ones, and update permissions.
Pushing all images into the same repository
would allow to more streamlined updates, and
ease maintenance.
=> containers: unify test image

.github/workflows/ci.yml
Use new repository (ovirt-imageio-test )in the pipelines.
=> ci.yml: use new repository

ovirt_imageio/client/_download.py, ovirt_imageio/client/_options.py, ovirt_imageio/client/_upload.py, test/client_options_test.py
Allow insecure connections using ovirt-img through a command line option.
Fixes: #153
=> client: add --insecure option

CODEOWNERS
This does not work with github since docs team does not have write access, and we never got any contribution anyway. We can ask manually for review if needed.
=> Remove docs team ownership

containers/centos-8.containerfile
Adds Python 3.9 support to CS8 container in order to prepare to support
the project in ansible-core 2.13, which uses Python 3.9
Signed-off-by: Martin Perina <mperina@redhat.com>
=> Add Python 3.9 support to CS8 container

.github/workflows/ci.yml, containers/centos-8.containerfile, ovirt-imageio.spec.in, tox.ini
Switch from Python 3.8 to 3.9 on EL8 to be able to support
ansible-core-2.13
Signed-off-by: Martin Perina <mperina@redhat.com>
=> Switch from Python 3.8 to 3.9 on EL8

ovirt_imageio/_internal/qemu_nbd.py, storage.py, test/qemu_nbd_test.py
Add support for block devices in qemu_nbd module. This enables serving block devices
with the ovirt-imageio container and writing to block devices in the ovirt-img tool.
Based on #167, adding basic tests.
=> Support block devices in qemu_nbd

ovirt_imageio/client/_download.py, ovirt_imageio/client/_options.py, ovirt_imageio/client/_ui.py, ovirt_imageio/client/_upload.py, test/client_options_test.py, test/client_ui_test.py
Add --output option to ovirt-img, so that
the output format for the progress is set
from the CLI.
Add json as an output option, to print
the progress in jsonlines[1] format.
A consistent machine readable format, that
can be later parsed.
```
$ ovirt-img  download-disk -c engine --output json <disk_id> download.raw
{"transferred": 0, elapsed: 0.0, "description": "setting up"}
...
{"transferred": 249561088, "size": 261095424, elapsed: 1.234567, "description": "downloading image"}
{"transferred": 256901120, "size": 261095424, elapsed: 1.345678, "description": "downloading image"}
{"transferred": 261095424, "size": 261095424, elapsed: 1.456789, "description": "finalizing transfer"}
...
```
[1] https://jsonlines.org/
Fixes: https://github.com/oVirt/ovirt-imageio/issues/154
Signed-off-by: …
=> ovirt-img: add --output format option

containers/centos-8.containerfile, containers/centos-9.containerfile, containers/fedora-36.containerfile, containers/fedora-37.containerfile, containers/fedora-38.containerfile
In test containers, create a
new venv [1] at /venv instead of installing
the required packages directly in the
root environment. Installing packages in
the root environment is strongly discouraged,
as it can run into conflicts with the system
package manager.
[1] - https://pip.pypa.io/warnings/venv
=> containers: create venv for tests

ci/test.sh, tox.ini
Activate containers venv before running
tests in the pipeline.
=> ci test: activate venv before tests

containers/centos-9.containerfile
This patch adds python3.11 dependencies to the centos 9 build container file.
Required by https://github.com/oVirt/ovirt-imageio/pull/178
=> Add python3.11 dependencies to centos-9-containerfile

ovirt_imageio/admin/tool.py
In the same way we do in ovirt-img - running without arguments is the same as -h, --help.
Example run:
$ ./ovirt-imageioctl
usage: ovirt-imageioctl [-h] {add-ticket,show-ticket,mod-ticket,del-ticket,start-profile,stop-profile} ...
Control the ovirt-imageio service
options:
-h, --help            show this help message and exit
commands:
{add-ticket,show-ticket,mod-ticket,del-ticket,start-profile,stop-profile}
add-ticket          Add a ticket.
show-ticket         Show a ticket status.
mod-ticket          Modify a ticket.
del-ticket          Delete a ticket.
start-profile       Start server profiling
stop-profile        Stop server profiling
Reported in:
https://github.com/oVirt/ovirt-imageio/pull/194#issuecomment-1463404284
=> Fix ovirt-imageioctl without arguments

containers/centos-8.containerfile
Currently the package is missing from c8s AppStream [1]. We can remove it for now.
[1] https://issues.redhat.com/browse/CS-1502
Fixes: 8e4957e
=> containers: remove python3.11-pip from c8s

examples/imageio-client
There was a typo in the example, 
$ ./ovit-imageio -c test -> $ ./ovirt-imageio -c test
=> fixed typo in imageio-client example

ovirt_imageio/_internal/auth.py, ovirt_imageio/_internal/handlers/tickets.py, test/handlers/tickets_test.py
Change remaining instances of errors.TicketCancelTimeout to errors.TransferCancelTimeout.
Include an initial unit test that attempts to mimic two connection attempts:
-  Connection 1 initiates the transfer
-   Connection 2 issues the delete request
-   The timeout is set to 0.0001 seconds, which seemed fast enough to raise a 409 conflict
Fixes #208
=> Attribute error during timeout cancelling transfer

ovirt_imageio/client/_options.py, test/client_options_test.py
ovirt-img add_sub_command method's help and func parameters now have
default values that are set to "help" and a no-op lambda func,
respectively, to simplify method usage in test cases. Method calls
referencing the add_sub_command method have also been cleaned up
accordingly.
Fixes #120 
Signed-off-by: sri-srikanth <srivatsansrikanth2018@gmail.com>
=> Default values for ovirt-img add_sub_command method added
